import { asyncHandler, AppError } from '../lib/route-utils.mjs';

export function registerPlannerRoutes(app, sprintEngine) {
  app.get(
    '/api/v1/planner/summary',
    asyncHandler(async (req, res) => {
      const summary = await sprintEngine.getSummary();
      res.json(summary);
    }),
  );

  app.get(
    '/api/v1/planner/items',
    asyncHandler(async (req, res) => {
      const opts = {};
      const { type, status, sprint, epic, priority, label, search, sortBy, autoGenerated } = req.query;
      if (type) opts.type = type;
      if (status) opts.status = status;
      if (sprint) opts.sprint = sprint;
      if (epic) opts.epic = epic;
      if (priority) opts.priority = priority;
      if (label) opts.label = label;
      if (search) opts.search = search;
      if (sortBy) opts.sortBy = sortBy;
      if (autoGenerated !== undefined) opts.autoGenerated = autoGenerated === 'true';
      const items = await sprintEngine.listItems(opts);
      res.json({ items, count: items.length });
    }),
  );

  app.post(
    '/api/v1/planner/items',
    asyncHandler(async (req, res) => {
      const item = await sprintEngine.createItem(req.body);
      res.status(201).json(item);
    }),
  );

  app.get(
    '/api/v1/planner/items/:itemId',
    asyncHandler(async (req, res) => {
      const { itemId } = req.params;
      try {
        const item = await sprintEngine.getItem(itemId);
        res.json(item);
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Item not found: ${itemId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.patch(
    '/api/v1/planner/items/:itemId',
    asyncHandler(async (req, res) => {
      const { itemId } = req.params;
      const updates = req.body;
      try {
        const item = await sprintEngine.updateItem(itemId, updates);
        res.json(item);
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Item not found: ${itemId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.delete(
    '/api/v1/planner/items/:itemId',
    asyncHandler(async (req, res) => {
      const { itemId } = req.params;
      try {
        await sprintEngine.deleteItem(itemId);
        res.json({ success: true, id: itemId });
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Item not found: ${itemId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.post(
    '/api/v1/planner/items/:itemId/feedback',
    asyncHandler(async (req, res) => {
      const { itemId } = req.params;
      const { action } = req.body;
      if (!action) throw new AppError('Action is required (accept, reject, or edit)', 400);
      if (!['accept', 'reject', 'edit'].includes(action)) {
        throw new AppError(`Invalid action: ${action}. Must be accept, reject, or edit`, 400);
      }
      try {
        const patterns = await sprintEngine.recordFeedback(itemId, action);
        res.json({ success: true, patterns });
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Item not found: ${itemId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.get(
    '/api/v1/planner/sprints',
    asyncHandler(async (req, res) => {
      const sprints = await sprintEngine.listSprints();
      res.json({ sprints, count: sprints.length });
    }),
  );

  app.post(
    '/api/v1/planner/sprints',
    asyncHandler(async (req, res) => {
      const sprint = await sprintEngine.createSprint(req.body);
      res.status(201).json(sprint);
    }),
  );

  app.get(
    '/api/v1/planner/sprints/:sprintId',
    asyncHandler(async (req, res) => {
      const { sprintId } = req.params;
      try {
        const sprint = await sprintEngine.getSprint(sprintId);
        res.json(sprint);
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Sprint not found: ${sprintId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.patch(
    '/api/v1/planner/sprints/:sprintId',
    asyncHandler(async (req, res) => {
      const { sprintId } = req.params;
      const updates = req.body;
      try {
        const sprint = await sprintEngine.updateSprint(sprintId, updates);
        res.json(sprint);
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Sprint not found: ${sprintId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.delete(
    '/api/v1/planner/sprints/:sprintId',
    asyncHandler(async (req, res) => {
      const { sprintId } = req.params;
      try {
        await sprintEngine.deleteSprint(sprintId);
        res.json({ success: true, id: sprintId });
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Sprint not found: ${sprintId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.get(
    '/api/v1/planner/sprints/:sprintId/report',
    asyncHandler(async (req, res) => {
      const { sprintId } = req.params;
      try {
        const report = await sprintEngine.generateSprintReport(sprintId);
        res.json(report);
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Sprint not found: ${sprintId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.post(
    '/api/v1/planner/sprints/:sprintId/items',
    asyncHandler(async (req, res) => {
      const { sprintId } = req.params;
      const { itemIds } = req.body;
      if (!itemIds || !Array.isArray(itemIds)) {
        throw new AppError('itemIds array is required', 400);
      }
      try {
        const sprint = await sprintEngine.addItemsToSprint(sprintId, itemIds);
        res.json(sprint);
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(err.message, 404);
        }
        throw err;
      }
    }),
  );

  app.post(
    '/api/v1/planner/sprints/:sprintId/items/remove',
    asyncHandler(async (req, res) => {
      const { sprintId } = req.params;
      const { itemIds } = req.body;
      if (!itemIds || !Array.isArray(itemIds)) {
        throw new AppError('itemIds array is required', 400);
      }
      try {
        const sprint = await sprintEngine.removeItemsFromSprint(sprintId, itemIds);
        res.json(sprint);
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(err.message, 404);
        }
        throw err;
      }
    }),
  );

  app.get(
    '/api/v1/planner/epics',
    asyncHandler(async (req, res) => {
      const epics = await sprintEngine.listEpics();
      res.json({ epics, count: epics.length });
    }),
  );

  app.post(
    '/api/v1/planner/epics',
    asyncHandler(async (req, res) => {
      const epic = await sprintEngine.createEpic(req.body);
      res.status(201).json(epic);
    }),
  );

  app.get(
    '/api/v1/planner/epics/:epicId',
    asyncHandler(async (req, res) => {
      const { epicId } = req.params;
      try {
        const epic = await sprintEngine.getEpic(epicId);
        res.json(epic);
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Epic not found: ${epicId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.patch(
    '/api/v1/planner/epics/:epicId',
    asyncHandler(async (req, res) => {
      const { epicId } = req.params;
      const updates = req.body;
      try {
        const epic = await sprintEngine.updateEpic(epicId, updates);
        res.json(epic);
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Epic not found: ${epicId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.delete(
    '/api/v1/planner/epics/:epicId',
    asyncHandler(async (req, res) => {
      const { epicId } = req.params;
      try {
        await sprintEngine.deleteEpic(epicId);
        res.json({ success: true, id: epicId });
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Epic not found: ${epicId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.get(
    '/api/v1/planner/initiatives',
    asyncHandler(async (req, res) => {
      const initiatives = await sprintEngine.listInitiatives();
      res.json({ initiatives, count: initiatives.length });
    }),
  );

  app.post(
    '/api/v1/planner/initiatives',
    asyncHandler(async (req, res) => {
      const initiative = await sprintEngine.createInitiative(req.body);
      res.status(201).json(initiative);
    }),
  );

  app.delete(
    '/api/v1/planner/initiatives/:initiativeId',
    asyncHandler(async (req, res) => {
      const { initiativeId } = req.params;
      try {
        await sprintEngine.deleteInitiative(initiativeId);
        res.json({ success: true, id: initiativeId });
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Initiative not found: ${initiativeId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.post(
    '/api/v1/planner/brainstorm',
    asyncHandler(async (req, res) => {
      const { context, prompts } = req.body;
      if (!prompts || !prompts.features) {
        throw new AppError('prompts.features is required for brainstorming', 400);
      }
      const result = await sprintEngine.brainstorm(context || {}, prompts || {});
      if (result.suggestions && result.suggestions.length > 0) {
        const createdItems = [];
        for (const suggestion of result.suggestions) {
          try {
            const item = await sprintEngine.createItem({
              ...suggestion,
              type: suggestion.type || 'task',
              title: suggestion.title,
              priority: suggestion.priority || 'P2',
            });
            createdItems.push(item);
          } catch (err) {
            throw new AppError(`Failed to create brainstorm item: ${err.message}`, 400);
          }
        }
        res.json({ suggestions: createdItems, context: result.context, count: createdItems.length });
      } else {
        res.json({ suggestions: [], context: result.context, count: 0 });
      }
    }),
  );

  app.post(
    '/api/v1/planner/items/:itemId/estimate',
    asyncHandler(async (req, res) => {
      const { itemId } = req.params;
      try {
        const estimate = await sprintEngine.estimateItem(itemId);
        res.json(estimate);
      } catch (err) {
        if (err.message.includes('not found')) {
          throw new AppError(`Item not found: ${itemId}`, 404);
        }
        throw err;
      }
    }),
  );

  app.post(
    '/api/v1/planner/auto-prioritize',
    asyncHandler(async (req, res) => {
      const { recentChanges, deadlines } = req.body || {};
      const prioritized = await sprintEngine.autoPrioritize({ recentChanges, deadlines });
      res.json({ items: prioritized, count: prioritized.length });
    }),
  );

  app.post(
    '/api/v1/planner/items/:itemId/link-decision/:decisionId',
    asyncHandler(async (req, res) => {
      const { itemId, decisionId } = req.params;
      const { relationship } = req.body;

      if (!itemId) throw new AppError('Item ID is required', 400);
      if (!decisionId) throw new AppError('Decision ID is required', 400);

      try {
        const result = await sprintEngine.linkDecisionToItem(itemId, decisionId, relationship);
        res.json({ success: true, ...result });
      } catch (err) {
        if (err.message.includes('not found')) {
          if (err.message.includes('Item')) {
            throw new AppError(`Item not found: ${itemId}`, 404);
          } else {
            throw new AppError(`Decision not found: ${decisionId}`, 404);
          }
        }
        if (err.message.includes('not configured')) {
          throw new AppError('Decision engine integration not available', 501);
        }
        throw err;
      }
    }),
  );

  app.get(
    '/api/v1/planner/items/:itemId/decisions',
    asyncHandler(async (req, res) => {
      const { itemId } = req.params;
      if (!itemId) throw new AppError('Item ID is required', 400);

      try {
        const decisions = await sprintEngine.getDecisionsForItem(itemId);
        res.json({ decisions, count: decisions.length });
      } catch (err) {
        if (err.message.includes('Item not found')) {
          throw new AppError(`Item not found: ${itemId}`, 404);
        }
        if (err.message.includes('not configured')) {
          throw new AppError('Decision engine integration not available', 501);
        }
        throw err;
      }
    }),
  );

  app.get(
    '/api/v1/planner/decisions/:decisionId/items',
    asyncHandler(async (req, res) => {
      const { decisionId } = req.params;
      if (!decisionId) throw new AppError('Decision ID is required', 400);

      try {
        const items = await sprintEngine.getItemsForDecision(decisionId);
        res.json({ items, count: items.length });
      } catch (err) {
        if (err.message.includes('Decision not found')) {
          throw new AppError(`Decision not found: ${decisionId}`, 404);
        }
        if (err.message.includes('not configured')) {
          throw new AppError('Decision engine integration not available', 501);
        }
        throw err;
      }
    }),
  );
}
