import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { SprintEngine } from '../daemon/lib/sprint-engine.mjs';

function makeFixture(name) {
  return fs.mkdtempSync(path.join(os.tmpdir(), `nokta-planner-${name}-`));
}

test('SprintEngine creates and retrieves items', async () => {
  const root = makeFixture('crud');
  const engine = new SprintEngine(root);

  const item = await engine.createItem({ type: 'task', title: 'Test task', priority: 'P1' });
  assert.ok(item.id.startsWith('NOK-'));
  assert.equal(item.title, 'Test task');
  assert.equal(item.type, 'task');
  assert.equal(item.priority, 'P1');
  assert.equal(item.status, 'backlog');

  const retrieved = await engine.getItem(item.id);
  assert.equal(retrieved.id, item.id);
  assert.equal(retrieved.title, 'Test task');
});

test('SprintEngine updates items', async () => {
  const root = makeFixture('update');
  const engine = new SprintEngine(root);

  const item = await engine.createItem({ type: 'story', title: 'Initial title' });
  const updated = await engine.updateItem(item.id, { title: 'Updated title', status: 'in-progress' });
  assert.equal(updated.title, 'Updated title');
  assert.equal(updated.status, 'in-progress');

  const fetched = await engine.getItem(item.id);
  assert.equal(fetched.title, 'Updated title');
  assert.equal(fetched.status, 'in-progress');
});

test('SprintEngine lists items with filters', async () => {
  const root = makeFixture('filter');
  const engine = new SprintEngine(root);

  await engine.createItem({ type: 'task', title: 'Task A', priority: 'P1', status: 'backlog' });
  await engine.createItem({ type: 'story', title: 'Story B', priority: 'P2', status: 'in-progress' });
  await engine.createItem({ type: 'bug', title: 'Bug C', priority: 'P0', status: 'done' });

  const all = await engine.listItems();
  assert.equal(all.length, 3);

  const tasks = await engine.listItems({ type: 'task' });
  assert.equal(tasks.length, 1);

  const done = await engine.listItems({ status: 'done' });
  assert.equal(done.length, 1);

  const p0 = await engine.listItems({ priority: 'P0' });
  assert.equal(p0.length, 1);
});

test('SprintEngine creates and manages epics', async () => {
  const root = makeFixture('epics');
  const engine = new SprintEngine(root);

  const epic = await engine.createEpic({ title: 'Auth Epic' });
  assert.ok(epic.id.startsWith('EPIC-'));

  await engine.createItem({ type: 'story', title: 'Login', epic: epic.id });
  await engine.createItem({ type: 'story', title: 'Register', epic: epic.id });

  const items = await engine.listItems({ epic: epic.id });
  assert.equal(items.length, 2);
});

test('SprintEngine creates and manages sprints', async () => {
  const root = makeFixture('sprints');
  const engine = new SprintEngine(root);

  const sprint = await engine.createSprint({ goal: 'Sprint 1', status: 'active' });
  assert.ok(sprint.id.startsWith('S'));

  const item = await engine.createItem({ type: 'task', title: 'Sprint task' });
  const updated = await engine.addItemsToSprint(sprint.id, [item.id]);
  assert.equal(updated.itemCount, 1);
  assert.equal((await engine.getSprint(sprint.id)).itemIds.length, 1);
});

test('SprintEngine brainstorm generates suggestions', async () => {
  const root = makeFixture('brainstorm');
  const engine = new SprintEngine(root);

  const result = await engine.brainstorm(
    { stacks: ['node', 'typescript'], files: ['src/index.ts'] },
    { features: 'Add user authentication', techDebt: true, testing: true },
  );
  assert.ok(result.suggestions.length >= 3);
  const featureSuggestion = result.suggestions.find((s) => s.title.includes('Brainstorm'));
  assert.ok(featureSuggestion);
  assert.ok(featureSuggestion.autoGenerated);
});

test('SprintEngine pr review detects issues', async () => {
  const root = makeFixture('pr');
  const engine = new SprintEngine(root);

  const diff = `diff --git a/src/auth.ts b/src/auth.ts
+function login() {
+  console.log("logging in");
+  const apiKey = "sk-123456";
+  debugger;
+  return true;
+}`;

  const result = await engine.reviewPR('feature/login', diff);
  assert.equal(result.summary.issuesFound, 3);
  assert.ok(result.comments.some((c) => c.rule === 'errorHandling'));
  assert.ok(result.comments.some((c) => c.rule === 'hardcodedSecrets'));
  assert.ok(result.comments.some((c) => c.rule === 'debugLeftovers'));
});

test('SprintEngine generates sprint report', async () => {
  const root = makeFixture('report');
  const engine = new SprintEngine(root);

  const sprint = await engine.createSprint({
    goal: 'Test Sprint',
    startDate: '2025-01-01',
    endDate: '2025-01-14',
    status: 'active',
  });

  const _item1 = await engine.createItem({ type: 'task', title: 'Task 1', sprint: sprint.id });
  const item2 = await engine.createItem({ type: 'story', title: 'Story 1', sprint: sprint.id });

  await engine.updateItem([_item1.id, item2.id][1], { status: 'done' });

  const report = await engine.generateSprintReport(sprint.id);
  assert.equal(report.totalItems, 2);
  assert.equal(report.completedItems, 1);
  assert.equal(report.completionRate, 50);
  assert.equal(report.byType.tasks, 1);
  assert.equal(report.byType.stories, 1);
});

test('SprintEngine self-learning tracks feedback', async () => {
  const root = makeFixture('learn');
  const engine = new SprintEngine(root);

  const item = await engine.createItem({
    type: 'task',
    title: 'Learn task',
    labels: ['frontend'],
    priority: 'P1',
    autoGenerated: true,
  });

  await engine.recordFeedback(item.id, 'accept');
  const patterns = await engine.getLearnedPatterns();
  assert.equal(patterns.acceptedItems, 1);
  assert.ok(patterns.commonLabels.includes('frontend'));
  assert.equal(patterns.commonPriorities.P1, 1);
});

test('SprintEngine estimateItem returns story points', async () => {
  const root = makeFixture('estimate');
  const engine = new SprintEngine(root);

  const item = await engine.createItem({
    type: 'story',
    title: 'Complex feature',
    labels: ['backend', 'api', 'typescript', 'database'],
    relatedFiles: ['src/service.ts', 'src/model.ts', 'src/controller.ts'],
    acceptanceCriteria: ['User can do X', 'System handles Y'],
    evidence: ['src/similar.ts', 'src/other.ts', 'src/docs.md'],
  });

  const estimate = await engine.estimateItem(item.id);
  assert.ok(estimate.storyPoints >= 1);
  assert.ok(estimate.confidence >= 0);
  assert.equal(estimate.itemId, item.id);
  assert.ok(estimate.breakdown.baseType === 8);
});

test('SprintEngine estimateItem handles missing item', async () => {
  const root = makeFixture('estimate-missing');
  const engine = new SprintEngine(root);

  await assert.rejects(
    () => engine.estimateItem('NOK-9999'),
    /Item not found/,
  );
});

test('SprintEngine autoPrioritize ranks items by priority and dependencies', async () => {
  const root = makeFixture('prioritize');
  const engine = new SprintEngine(root);

  const item1 = await engine.createItem({ type: 'task', title: 'P0 task', priority: 'P0' });
  const _item2 = await engine.createItem({ type: 'story', title: 'P2 story', priority: 'P2' });
  const item3 = await engine.createItem({
    type: 'task',
    title: 'Dependent task',
    priority: 'P2',
    dependencies: [item1.id],
  });

  const prioritized = await engine.autoPrioritize({});
  assert.equal(prioritized.length, 3);
  assert.ok(prioritized[0].priorityScore > prioritized[1].priorityScore);
  // item1 (P0) should rank highest
  assert.equal(prioritized[0].id, item1.id);
  // item3 depends on item1, so should get a dependency bonus
  const item3Result = prioritized.find((p) => p.id === item3.id);
  assert.ok(item3Result.priorityScore > 0);
});

test('SprintEngine autoPrioritize handles empty backlog', async () => {
  const root = makeFixture('prioritize-empty');
  const engine = new SprintEngine(root);

  const prioritized = await engine.autoPrioritize({});
  assert.equal(prioritized.length, 0);
});

test('SprintEngine auto-update detects file changes', async () => {
  const root = makeFixture('autoupdate');
  const engine = new SprintEngine(root);

  const item = await engine.createItem({
    type: 'story',
    title: 'Auth Feature',
    status: 'in-progress',
    relatedFiles: ['src/auth/login.ts'],
  });

  const result = await engine.autoUpdate({
    file: 'src/auth/login.ts',
    eventType: 'change',
  });

  assert.equal(result.length, 1);
  assert.equal(result[0].id, item.id);
  assert.equal(result[0].newStatus, 'review');
});

test('SprintEngine getSummary returns correct counts', async () => {
  const root = makeFixture('summary');
  const engine = new SprintEngine(root);

  await engine.createItem({ type: 'task', title: 'T1', status: 'backlog' });
  await engine.createItem({ type: 'task', title: 'T2', status: 'in-progress' });
  await engine.createItem({ type: 'bug', title: 'B1', status: 'done' });
  await engine.createEpic({ title: 'Epic' });
  await engine.createSprint({ goal: 'S1' });

  const summary = await engine.getSummary();
  assert.equal(summary.totalItems, 3);
  assert.equal(summary.byStatus.backlog, 1);
  assert.equal(summary.byStatus.inProgress, 1);
  assert.equal(summary.byStatus.done, 1);
  assert.equal(summary.epics, 1);
  assert.equal(summary.sprints, 1);
});
